import type {
  AdvancedSettings,
  AdvancedSettingsSync,
  AsteroidDensity,
  BaseGameMode,
  GameMode,
  GamePhase,
  Hooks,
  HomingMissileState,
  LaserBeamState,
  MapId,
  MineState,
  ModePreset,
  PlayerInput,
  PlayerPowerUp,
  PlayerState,
  PilotState,
  PowerUpState,
  PowerUpType,
  ProjectileState,
  RoundResultPayload,
  ShipState,
  SnapshotPayload,
  SpeedPreset,
  DashPreset,
  TurretBulletState,
  TurretState,
  AsteroidState,
} from "../sim/types.js";
import {
  ARENA_HEIGHT,
  ARENA_PADDING,
  ARENA_WIDTH,
  ASTEROID_DAMAGE_SHIPS,
  ASTEROID_DROP_CHANCE,
  ASTEROID_FRICTION,
  ASTEROID_INITIAL_MAX,
  ASTEROID_INITIAL_MIN,
  ASTEROID_LARGE_MAX,
  ASTEROID_LARGE_MIN,
  ASTEROID_RESTITUTION,
  ASTEROID_SMALL_MAX,
  ASTEROID_SMALL_MIN,
  ASTEROID_SPAWN_BATCH_MAX,
  ASTEROID_SPAWN_BATCH_MIN,
  ASTEROID_SPAWN_INTERVAL_MAX_MS,
  ASTEROID_SPAWN_INTERVAL_MIN_MS,
  ASTEROID_SPLIT_COUNT,
  ASTEROID_VERTICES_MAX,
  ASTEROID_VERTICES_MIN,
  CHAOTIC_CONFIG,
  COUNTDOWN_SECONDS,
  DEFAULT_ADVANCED_SETTINGS,
  FIRE_COOLDOWN_MS,
  HOMING_MISSILE_ACCURACY,
  HOMING_MISSILE_DETECTION_RADIUS,
  HOMING_MISSILE_LIFETIME_MS,
  HOMING_MISSILE_SPEED,
  HOMING_MISSILE_TURN_RATE,
  LASER_BEAM_LENGTH,
  LASER_CHARGES,
  LASER_COOLDOWN_MS,
  MAX_AMMO,
  MINE_EXPLOSION_RADIUS,
  MINE_SIZE,
  PILOT_ANGULAR_DAMPING,
  PILOT_DASH_COOLDOWN_MS,
  PILOT_FRICTION_AIR,
  PILOT_SURVIVAL_MS,
  PLAYER_COLORS as SIM_PLAYER_COLORS,
  POWERUP_DESPAWN_MS,
  POWERUP_SHIELD_HITS,
  POWERUP_SPAWN_WEIGHTS,
  PROJECTILE_LIFETIME_MS,
  PROJECTILE_SPEED,
  RELOAD_MS,
  ROUND_RESULTS_DURATION_MS,
  SANE_CONFIG,
  SCATTER_ANGLE_DEG,
  SCATTER_CHARGES,
  SCATTER_COOLDOWN_MS,
  SCATTER_PROJECTILE_LIFETIME_MS,
  SCATTER_PROJECTILE_SPEED,
  SHIP_ANGULAR_DAMPING_BY_PRESET,
  SHIP_FRICTION_AIR_BY_PRESET,
  SHIP_FRICTION_BY_PRESET,
  SHIP_RESTITUTION_BY_PRESET,
  STANDARD_CONFIG,
  WALL_FRICTION_BY_PRESET,
  WALL_RESTITUTION_BY_PRESET,
} from "../sim/constants.js";

export type {
  AdvancedSettings,
  AdvancedSettingsSync,
  AsteroidDensity,
  AsteroidState,
  BaseGameMode,
  DashPreset,
  GameMode,
  GamePhase,
  HomingMissileState,
  Hooks,
  LaserBeamState,
  MapId,
  MineState,
  ModePreset,
  PilotState,
  PlayerInput,
  PlayerPowerUp,
  PlayerState,
  PowerUpState,
  PowerUpType,
  ProjectileState,
  RoundResultPayload,
  ShipState,
  SpeedPreset,
  TurretBulletState,
  TurretState,
};

export type GameStateSync = SnapshotPayload;

export interface PlayerColor {
  primary: string;
  glow: string;
}

export interface PlayerData {
  id: string;
  name: string;
  color: PlayerColor;
  kills: number;
  roundWins: number;
  state: PlayerState;
}

export interface DashParticleEvent {
  playerId: string;
  x: number;
  y: number;
  angle: number;
  timestamp: number;
  color: string;
}

export interface Settings {
  music: boolean;
  fx: boolean;
  haptics: boolean;
  controlHints: boolean;
}

export interface Particle {
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  maxLife: number;
  size: number;
  color: string;
}

export const PLAYER_COLORS: PlayerColor[] = SIM_PLAYER_COLORS.map((entry) => ({
  primary: entry.primary,
  glow: entry.glow,
}));

export const STANDARD_PHYSICS = {
  WALL_RESTITUTION: WALL_RESTITUTION_BY_PRESET.STANDARD,
  WALL_FRICTION: WALL_FRICTION_BY_PRESET.STANDARD,
  SHIP_FRICTION: SHIP_FRICTION_BY_PRESET.STANDARD,
  SHIP_ANGULAR_DAMPING: SHIP_ANGULAR_DAMPING_BY_PRESET.STANDARD,
};

export const SANE_PHYSICS = {
  WALL_RESTITUTION: WALL_RESTITUTION_BY_PRESET.SANE,
  WALL_FRICTION: WALL_FRICTION_BY_PRESET.SANE,
  SHIP_FRICTION: SHIP_FRICTION_BY_PRESET.SANE,
  SHIP_ANGULAR_DAMPING: SHIP_ANGULAR_DAMPING_BY_PRESET.SANE,
};

export const CHAOTIC_PHYSICS = {
  WALL_RESTITUTION: WALL_RESTITUTION_BY_PRESET.CHAOTIC,
  WALL_FRICTION: WALL_FRICTION_BY_PRESET.CHAOTIC,
  SHIP_FRICTION: SHIP_FRICTION_BY_PRESET.CHAOTIC,
  SHIP_ANGULAR_DAMPING: SHIP_ANGULAR_DAMPING_BY_PRESET.CHAOTIC,
};

export const GAME_CONFIG = {
  KILLS_TO_WIN: 5,
  ROUNDS_TO_WIN: 3,
  ARENA_WIDTH,
  ARENA_HEIGHT,
  ARENA_PADDING,
  BASE_THRUST: CHAOTIC_CONFIG.BASE_THRUST,
  ROTATION_SPEED: CHAOTIC_CONFIG.ROTATION_SPEED,
  ROTATION_THRUST_BONUS: CHAOTIC_CONFIG.ROTATION_THRUST_BONUS,
  RECOIL_FORCE: CHAOTIC_CONFIG.RECOIL_FORCE,
  DASH_FORCE: CHAOTIC_CONFIG.DASH_FORCE,
  SHIP_FRICTION_AIR: CHAOTIC_CONFIG.SHIP_FRICTION_AIR,
  SHIP_RESTITUTION: CHAOTIC_CONFIG.SHIP_RESTITUTION,
  SHIP_TARGET_SPEED: CHAOTIC_CONFIG.SHIP_TARGET_SPEED,
  SHIP_SPEED_RESPONSE: CHAOTIC_CONFIG.SHIP_SPEED_RESPONSE,
  SHIP_DASH_BOOST: CHAOTIC_CONFIG.SHIP_DASH_BOOST,
  SHIP_DASH_DURATION: CHAOTIC_CONFIG.SHIP_DASH_DURATION,
  SHIP_RECOIL_SLOWDOWN: CHAOTIC_CONFIG.SHIP_RECOIL_SLOWDOWN,
  SHIP_RECOIL_DURATION: CHAOTIC_CONFIG.SHIP_RECOIL_DURATION,
  FIRE_COOLDOWN: FIRE_COOLDOWN_MS,
  PROJECTILE_SPEED,
  PROJECTILE_LIFETIME: PROJECTILE_LIFETIME_MS,
  MAX_AMMO,
  AMMO_RELOAD_TIME: RELOAD_MS,
  AMMO_BURST_DELAY: 150,
  PILOT_SURVIVAL_TIME: PILOT_SURVIVAL_MS,
  PILOT_FRICTION_AIR,
  PILOT_ROTATION_SPEED: STANDARD_CONFIG.PILOT_ROTATION_SPEED,
  PILOT_DASH_FORCE: STANDARD_CONFIG.PILOT_DASH_FORCE,
  PILOT_DASH_COOLDOWN: PILOT_DASH_COOLDOWN_MS,
  PILOT_EJECT_VELOCITY_SCALE: 0.7,
  PILOT_ANGULAR_DAMPING,
  INVULNERABLE_TIME: 2000,
  SYNC_INTERVAL: 50,
  COUNTDOWN_DURATION: COUNTDOWN_SECONDS,
  ROUND_RESULTS_DURATION: ROUND_RESULTS_DURATION_MS / 1000,
  ASTEROID_INITIAL_MIN,
  ASTEROID_INITIAL_MAX,
  ASTEROID_LARGE_MIN,
  ASTEROID_LARGE_MAX,
  ASTEROID_SMALL_MIN,
  ASTEROID_SMALL_MAX,
  ASTEROID_DRIFT_MIN_SPEED: 0.6,
  ASTEROID_DRIFT_MAX_SPEED: 1.6,
  ASTEROID_SPLIT_COUNT,
  ASTEROID_RESTITUTION,
  ASTEROID_FRICTION,
  ASTEROID_DAMAGE_SHIPS,
  ASTEROID_VERTICES_MIN,
  ASTEROID_VERTICES_MAX,
  ASTEROID_COLOR: "#ff8800",
  ASTEROID_GLOW: "#ff4400",
  GREY_ASTEROID_COLOR: "#888899",
  GREY_ASTEROID_GLOW: "#666677",
  ASTEROID_SPAWN_INTERVAL_MIN: ASTEROID_SPAWN_INTERVAL_MIN_MS,
  ASTEROID_SPAWN_INTERVAL_MAX: ASTEROID_SPAWN_INTERVAL_MAX_MS,
  ASTEROID_SPAWN_BATCH_MIN,
  ASTEROID_SPAWN_BATCH_MAX,
  ASTEROID_SPAWN_MARGIN: 100,
  POWERUP_DESPAWN_TIME: POWERUP_DESPAWN_MS,
  POWERUP_DROP_CHANCE: ASTEROID_DROP_CHANCE,
  POWERUP_SPAWN_WEIGHTS,
  POWERUP_SIZE: 25,
  POWERUP_LASER_CHARGES: LASER_CHARGES,
  POWERUP_LASER_COOLDOWN: LASER_COOLDOWN_MS,
  POWERUP_SHIELD_HITS,
  POWERUP_BEAM_LENGTH: LASER_BEAM_LENGTH,
  POWERUP_BEAM_WIDTH: 8,
  POWERUP_SCATTER_CHARGES: SCATTER_CHARGES,
  POWERUP_SCATTER_COOLDOWN: SCATTER_COOLDOWN_MS,
  POWERUP_SCATTER_ANGLE_1: SCATTER_ANGLE_DEG,
  POWERUP_SCATTER_ANGLE_2: 30,
  POWERUP_SCATTER_ANGLE_3: 45,
  POWERUP_SCATTER_PROJECTILE_SPEED: SCATTER_PROJECTILE_SPEED,
  POWERUP_SCATTER_PROJECTILE_LIFETIME: SCATTER_PROJECTILE_LIFETIME_MS,
  POWERUP_MINE_DESPAWN_TIME: 30000,
  POWERUP_MINE_EXPLOSION_RADIUS: MINE_EXPLOSION_RADIUS,
  POWERUP_MINE_SIZE: MINE_SIZE,
  POWERUP_JOUST_SIZE: 35,
  POWERUP_JOUST_WIDTH: 4,
  POWERUP_JOUST_OFFSET: 22,
  POWERUP_HOMING_MISSILE_SPEED: HOMING_MISSILE_SPEED,
  POWERUP_HOMING_MISSILE_TURN_RATE: HOMING_MISSILE_TURN_RATE,
  POWERUP_HOMING_MISSILE_LIFETIME: HOMING_MISSILE_LIFETIME_MS,
  POWERUP_HOMING_MISSILE_ACCURACY: HOMING_MISSILE_ACCURACY,
  POWERUP_HOMING_MISSILE_DETECTION_RADIUS: HOMING_MISSILE_DETECTION_RADIUS,
} as const;

export type GameConfigType = {
  -readonly [K in keyof typeof GAME_CONFIG]: (typeof GAME_CONFIG)[K] extends number
    ? number
    : (typeof GAME_CONFIG)[K] extends string
      ? string
      : (typeof GAME_CONFIG)[K];
};

export const STANDARD_OVERRIDES: Partial<GameConfigType> = {
  BASE_THRUST: STANDARD_CONFIG.BASE_THRUST,
  ROTATION_SPEED: STANDARD_CONFIG.ROTATION_SPEED,
  ROTATION_THRUST_BONUS: STANDARD_CONFIG.ROTATION_THRUST_BONUS,
  RECOIL_FORCE: STANDARD_CONFIG.RECOIL_FORCE,
  DASH_FORCE: STANDARD_CONFIG.DASH_FORCE,
  SHIP_FRICTION_AIR: STANDARD_CONFIG.SHIP_FRICTION_AIR,
  SHIP_RESTITUTION: STANDARD_CONFIG.SHIP_RESTITUTION,
};

export const SANE_OVERRIDES: Partial<GameConfigType> = {
  BASE_THRUST: SANE_CONFIG.BASE_THRUST,
  ROTATION_SPEED: SANE_CONFIG.ROTATION_SPEED,
  ROTATION_THRUST_BONUS: SANE_CONFIG.ROTATION_THRUST_BONUS,
  RECOIL_FORCE: SANE_CONFIG.RECOIL_FORCE,
  DASH_FORCE: SANE_CONFIG.DASH_FORCE,
  SHIP_FRICTION_AIR: SANE_CONFIG.SHIP_FRICTION_AIR,
  SHIP_RESTITUTION: SANE_CONFIG.SHIP_RESTITUTION,
};

export { DEFAULT_ADVANCED_SETTINGS };
