import { GAME_CONFIG } from "../../types";

export const NETWORK_GAME_FEEL_TUNING = {
  remoteSmoothing: {
    maxSnapshotBufferSize: 120,
    interpolationDelayBaseMs: 120,
    interpolationDelayMinMs: 80,
    interpolationDelayMaxMs: 220,
    interpolationDelayJitterScale: 1.5,
    interpolationDelaySmoothing: 0.15,
    extrapolationCapBaseMs: 110,
    extrapolationCapMinMs: 100,
    extrapolationCapMaxMs: 140,
    extrapolationCapJitterScale: 0.6,
    snapshotIntervalTargetMs: GAME_CONFIG.SYNC_INTERVAL,
    snapshotJitterSmoothing: 0.1,
  },
  selfPrediction: {
    enabled: true,
    fixedStepSec: 1 / 60,
    inputSendIntervalMs: 1000 / 60,
    maxPredictionStepsPerFrame: 8,
    maxPredictionAccumulatorSec: 0.2,
    historyLimitSteps: 360,
    maxFrameStepSec: 0.05,
    correctionThresholdPx: 15,
    softBlendThresholdPx: 40,
    hardSnapThresholdPx: 140,
    smallErrorBlendFactor: 0.2,
    softBlendFactor: 0.55,
    correctionOffsetDecayPerSec: 12,
    maxRenderOffsetPx: 180,
    nonStandardResponseScale: 0.75,
    unstableErrorThresholdPx: 48,
    unstableEwmaThresholdPx: 24,
    unstableFallbackDurationMs: 700,
    authoritativeFallbackExtrapolationMs: 55,
  },
  predictedLocalActionCosmetics: {
    fire: false,
    dash: false,
  },
  localAuthoritativeSoundSuppressionMs: {
    fire: 260,
    dash: 320,
  },
} as const;
